--CREATE SEQUENCE SEQ_PRODUCT;
--CREATE TABLE TBL_PRODUCT(
--	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
--	PRODUCT_NAME VARCHAR2(255) NOT NULL,
--	PRODUCT_PRICE NUMBER DEFAULT 0,
--	PRODUCT_STOCK NUMBER DEFAULT 999
--);
--
--
--SELECT * FROM TBL_PRODUCT;	


--CREATE SEQUENCE SEQ_POST;
--CREATE TABLE TBL_POST(
--	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
--	POST_TITLE VARCHAR2(255) NOT NULL,
--	POST_CONTENT VARCHAR2 (255) NOT NULL,
--	POST_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);
--
--SELECT * 
--FROM TBL_POST;
--
--INSERT INTO TBL_POST (ID, POST_TITLE, POST_CONTENT, POST_CREATE_AT)
--VALUES (SEQ_POST.NEXTVAL, '첫 글', '안녕하세요. 첫 게시글입니다.', SYSDATE);
--
--INSERT INTO TBL_POST (ID, POST_TITLE, POST_CONTENT, POST_CREATE_AT)
--VALUES (SEQ_POST.NEXTVAL, '공지', '점검 안내드립니다.', SYSDATE);
--
--INSERT INTO TBL_POST (ID, POST_TITLE, POST_CONTENT, POST_CREATE_AT)
--VALUES (SEQ_POST.NEXTVAL, '질문', 'MyBatis 매퍼가 헷갈려요.', SYSDATE);



CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2 (255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2 (255) NOT NULL,
	MEMBER_NAME VARCHAR2 (255) NOT NULL
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_COUNT NUMBER DEFAULT 1,
	PRODUCT_ID NUMBER ,
	MEMBER_ID NUMBER,
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID),
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
	);

SELECT * FROM TBL_MEMBER ;
SELECT * FROM TBL_ORDER ;

SELECT ID , MEMBER_EMAIL , MEMBER_PASSWORD , MEMBER_NAME 
FROM TBL_MEMBER 
WHERE MEMBER_EMAIL = 'test123@gmail.com'
	AND MEMBER_PASSWORD = 'test123!@#';

SELECT COUNT(*) IS_EXISTS
FROM TBL_MEMBER 
WHERE MEMBER_EMAIL = 'test123@gmail.com'

SELECT * FROM TBL_PRODUCT;

SELECT ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_STOCK
FROM TBL_PRODUCT
ORDER BY ID DESC ;


INSERT INTO TBL_PRODUCT
VALUSE (SEQ_PRODUCT.NEXTVAL, '노트북' ,1000000, 20);
