--CREATE SEQUENCE SEQ_PRODUCT;
--CREATE TABLE TBL_PRODUCT(
--	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
--	PRODUCT_NAME VARCHAR2(255) NOT NULL,
--	PRODUCT_PRICE NUMBER DEFAULT 0,
--	PRODUCT_STOCK NUMBER DEFAULT 999
--);
--
--
--SELECT * FROM TBL_PRODUCT;	


CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2 (255) NOT NULL,
	POST_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * 
FROM TBL_POST;

INSERT INTO TBL_POST (ID, POST_TITLE, POST_CONTENT, POST_CREATE_AT)
VALUES (SEQ_POST.NEXTVAL, '첫 글', '안녕하세요. 첫 게시글입니다.', SYSDATE);

INSERT INTO TBL_POST (ID, POST_TITLE, POST_CONTENT, POST_CREATE_AT)
VALUES (SEQ_POST.NEXTVAL, '공지', '점검 안내드립니다.', SYSDATE);

INSERT INTO TBL_POST (ID, POST_TITLE, POST_CONTENT, POST_CREATE_AT)
VALUES (SEQ_POST.NEXTVAL, '질문', 'MyBatis 매퍼가 헷갈려요.', SYSDATE);