CREATE SEQUENCE SEQ_POST_TEST;
CREATE TABLE TBL_POST_TEST(
	ID NUMBER CONSTRAINT PK_POST_TEST PRIMARY KEY,
	POST_TEST_TITLE VARCHAR2(255) NOT NULL,
	POST_TEST_CONTENT VARCHAR2(2555) NOT NULL
);

-- 게시글 추가
INSERT INTO TBL_POST_TEST 
VALUES(SEQ_POST_TEST.NEXTVAL, '규혁이는 바나가 좋아', '왜 좋을까. 흠');

INSERT INTO TBL_POST_TEST
VALUES(SEQ_POST_TEST.NEXTVAL, '왕밤빵', '맛이 좋아요');

INSERT INTO TBL_POST_TEST
VALUES(SEQ_POST_TEST.NEXTVAL, '삐용', '삐용삐용');

​-- 게시글 전체조회

SELECT ID "게시글 번호", POST_TEST_TITLE "게시글 제목", POST_TEST_CONTENT "게시글 내용"
FROM TBL_POST_TEST  
ORDER BY ID ;
 

-- 2번게시글 조회

SELECT ID "게시글 번호", POST_TEST_TITLE "게시글 제목", POST_TEST_CONTENT "게시글 내용"
FROM TBL_POST_TEST
WHERE ID = 2;

-- 3번 게시글 수정

UPDATE TBL_POST_TEST
SET POST_TEST_CONTENT = '삐용 수정 했어요'
WHERE ID = 3;

UPDATE TBL_POST_TEST
SET POST_TEST_TITLE = '게시글 제목 수정해요' , POST_TEST_CONTENT = '수정했어요'
WHERE ID = 3;
-- set으로 content의 값을 바꾼다.

-- 게시글 삭제

DELETE FROM TBL_POST_TEST
WHERE ID = 3;

SELECT * FROM TBL_POST_TEST;

SELECT ID "게시글 번호", POST_TEST_TITLE "제목", POST_TEST_CONTENT "내용"
FROM TBL_POST_TEST
ORDER BY ID;

